### PR TITLE
Deprecate private repositories and unify the design system

### PR DESCRIPTION
**Pull request by jrschumacher**
1. Removes all private dependencies #22 …

- virtru-typography
- virtru-design-params
- jest-config-virtru
…in favor of design tokens managed by Amazon's [Style Dictionary](https://amzn.github.io/style-dictionary/#/). 

2. Significant CSS cleanup: 

- replace old, unscoped CSS vars (e.g. `var(--small)` => `var(--vds-font-sm)`)
- use new design tokens 
- document stylelint rules 
- appease stylelint and note hacks to fix later

3. Confirms all changes above with Loki VRT.

### CODE REVIEW

**Comment by avkvirtru** [comment]
@jrschumacher massive update here… please review

but check THIS out 😎 (no checking out of branch required!)
https://deploy-preview-19--tender-almeida-90e742.netlify.app/?path=/docs/basics-design-tokens--page

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by jrschumacher** [comment]
:rocket: PR was released in [`v1.2.0`](https://github.com/avkvirtru/virtuoso-design-system/releases/tag/v1.2.0) :rocket:

**Comment by avkvirtru** [comment]
@jrschumacher did you have problems pushing the release? Lots of duplicate comments above…

**Comment by jrschumacher** [comment]
@avkvirtru Idk. I think it's based on the commits. Typically one commit per PR in OSS projects that I've used for conventional commits.

**Pull request merged**
