### PR TITLE
[PLAT-675] feat: add danger button

### PR DESCRIPTION
**Pull request by aleonov-virtru**
changes: _minor_

### Proposed Changes
- PLAT-675
  - add danger button

### Checklist

- [ ] I have added or updated unit tests
- [ ] I have added or updated integration tests (if appropriate)
- [ ] I have added or updated documentation / readme (if appropriate)
- [ ] I have verified that my changes have not introduced new lint errors
- [ ] I have updated the change log

### CODE REVIEW

**Comment by aleonov-virtru** [comment]
@jrschumacher Please check this out

**Comment by jrschumacher** [comment]
@aleonov-virtru actually we need to update the Loki snapshots probably. 

image

**Comment by jrschumacher** [comment]
@aleonov-virtru action items

- [ ] Update Loki snapshots to include the new danger state
- [ ] Add danger knob to button default story

**Comment by jrschumacher** [comment]
@aleonov-virtru approved

**Pull request merged**
